### ISSUE TITLE
Crashes when fastq.gz is empty

### ISSUE THREAD

**Issue by nimbusFarzaneh** [BCCDC-PHL/basic-sequence-qc#1]
fails because it is an empty fastq.gz file.

**Comment by dfornika** [comment]
When an empty fastq file is provided, the `seqtk fqchk` output looks something like this:

```csv
filename,position,num_bases,percent_a,percent_c,percent_g,percent_t,percent_n,average_q,error_q,percent_bases_below_q30,percent_bases_above_q30
empty.fastq.gz,ALL,0,-nan,-nan,-nan,-nan,-nan,-nan,-0.0,-nan,-nan
```
(the `seqtk fqchk` output doesn't include the header, only the second line)

The output is a single line, that includes `ALL`.

In these lines we use `grep` to collect stats by position. We do that by looking for any lines that don't include `ALL`:

https://github.com/BCCDC-PHL/basic-sequence-qc/blob/e0b178808a8daf26fb85aeaf18640dfa761ae603/modules/seqtk.nf#L18

https://github.com/BCCDC-PHL/basic-sequence-qc/blob/e0b178808a8daf26fb85aeaf18640dfa761ae603/modules/seqtk.nf#L21

The problem is that `grep -v` returns an error exit code `1` when it doesn't print any output. This causes the process and pipeline to crash.

We can follow an approach similar to the ones suggested here to force exit code `0` from those grep commands:

https://stackoverflow.com/a/36131305
